spring:
  application:
    name: spring_patry_apply_provider
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wisdompatry?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: admin
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

dubbo:
  scan:
    base-packages: com.smart.patry.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  application:
    name: dubbo_patry_apply_provider
  registry:
    address: nacos://nacos.funtl.com
    port: 8848
  provider:
    timeout: 30000
management:
  metrics:
    tags:
      application: spring_patry_apply_provider

mybatis:
  type-aliases-package: com.smart.patry.provider.domain
  mapper-locations: classpath:mapperxml/*.xml
